### ISSUE TITLE
Is there any problem on providing 16 bit values on arbotix_msgs/Analog messages?

### ISSUE THREAD

**Issue by corot** [vanadiumlabs/arbotix_ros#24]
I use arbotix_ros with an OpenCM9.04 Dinamixel board, that provides analog readings between 0 and ~2000. Instead of converting to 0..255, could we just change the message? I suppose this will have no impact on current use with ArbotiX boards.

**Comment by mikeferguson** [comment]
Other than the MD5 breakage, I see no issues here. It's really too late to break the hydro messages, but I think we could merge a PR for indigo.
