### ISSUE TITLE
Should we add enable/relax services to the Controller class?

### ISSUE THREAD

**Issue by corot** [vanadiumlabs/arbotix_ros#26]
So user don't need to call the service on any sevo. It's just a suggestion; maybe is too dynamixel-specific stuff to put here. For example, @pirobot has implemented the same in his own stack.

**Comment by mikeferguson** [comment]
I'm not sure what you mean exactly, could elaborate a bit on the use case?

**Comment by corot** [comment]
Sorry. I mean that, if I have, for example, the controllers to operate a trutlebot arm (gripper controller + follower controller), I will have 5 enable, 5 relax services, etc. one per joint. But it would also be good to have a single relax, a single enable, etc. service for the 4 joints in the arm controller.

**Comment by mikeferguson** [comment]
That seems pretty reasonable, I don't have time to implement, but a pull request is certainly welcome.

**Comment by corot** [comment]
Implemented here d87874b53a6d9a0f39eb2134bbc2278003ff5daf
