### ISSUE TITLE
HELP on maintaining arbotix_ros repo

### ISSUE THREAD

**Issue by corot** [vanadiumlabs/arbotix_ros#32]
Hi @mikeferguson,  it seems to me that you have no time at all to maintain this repo; would you like some help? 

I have notice that people (me included) are developing their own forks, wasting time on duplicated effort. I'll have some time in the following weeks, so I can at least help merging my changes and those from @croesmann.

Particularly, the gripper controller need a proper action server that waits for reached position. At least @croesmann and me did that in our forks.

**Comment by corot** [comment]
@mikeferguson

PING...

PING...

:grin:

**Comment by corot** [comment]
@mikeferguson     hellooooooooo...........

**Comment by robosamir** [comment]
+1

**Comment by mikeferguson** [comment]
@corot -- not sure if you're still interested in helping out. If you are, ping me here, and I can add you to the org. My only request would be that you give me a day or two to also help review PRs (since my name is still fairly associated with the ArbotiX stuff). Thanks!
