### ISSUE TITLE
How to use it in ros-kinetic?

### ISSUE THREAD

**Issue by dxls168** [vanadiumlabs/arbotix_ros#36]

**Comment by dxls168** [comment]
I have solved that.
                 you should't use command like  sudo apt-get install ros-kinetic-arbotix .
                 you should use command like  git clone https://github.com/vanadiumlabs/arbotix_ros.git,
                 then use catkin_make to make them.

**Comment by Abduoit** [comment]
@dxls168 
your solution will get indigo level branch
how to get kinetic branch ??

**Comment by mikeferguson** [comment]
Has now been released into Kinetic, should be available shortly: https://github.com/ros/rosdistro/pull/17336
