### ISSUE TITLE
Unable to install...

### ISSUE THREAD

**Issue by pitosalas** [vanadiumlabs/arbotix_ros#41]
Any idea why:

```
 sudo apt-get install ros-indigo-arbotix-*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-indigo-arbotix-*
E: Couldn't find any package by glob 'ros-indigo-arbotix-*'
E: Couldn't find any package by regex 'ros-indigo-arbotix-*'
pitosalas@ubuntu:~$ 

```
( modified by adding -* because I had misread instructions. But still doesn't work..)

**Comment by mikeferguson** [comment]
Those commands should work -- the packages are there. Make sure you've added the ROS APT repos and have successfully run "sudo apt-get update" (make sure there are no errors)
