### ISSUE TITLE
error loading <rosparam> tag   when i "roslaunch mrobot_description arbotix_mrobot_with_kinect.launch " 

### ISSUE THREAD

**Issue by zxchen3819** [vanadiumlabs/arbotix_ros#43]
Hello, when I execute "roslaunch mrobot_description arbotix_mrobot_with_kinect.launch"，The error that occurred is

error loading tag:
'ascii' codec can't decode byte 0xef in position 312: ordinal not in range(128)
XML is
The traceback for the exception was written to the log file

What should I do?

**Comment by zxchen3819** [comment]
I know the reason, because my file contains Chinese characters.Check and modify it

**Comment by mikeferguson** [comment]
Looks like you solved your issue.
