### ISSUE TITLE
follow_controller not reacting on STOP command of MoveIt

### ISSUE THREAD

**Issue by MarcoT11** [vanadiumlabs/arbotix_ros#44]
When I execute a trajectory in MoveIt RViz and press the stop button the motion of the robot arm doesn't stop. The console sais that the motion is stoped but in reality the motion is done until the destination is reached. I tried adding a 

`stop_trajectory_duration: 0.5`

in my .yaml file but without success. Here is the output of the console:

![Screenshot from 2019-08-23 15-57-35](https://user-images.githubusercontent.com/48487398/63597910-c3be5680-c5be-11e9-8015-c26b8b3761bf.png)

How can I stop a executed trajectory in the follow_controller?

**Comment by mikeferguson** [comment]
Archiving shortly
