### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?

### ISSUE THREAD

**Issue by hhxzzy** [vanadiumlabs/arbotix_ros#45]
Hello, I got this error when I execute a launch file.
![2020-06-02 23-30-20 的屏幕截图](https://user-images.githubusercontent.com/48182501/83538977-10a96300-a529-11ea-9011-cce564fb060c.png)
It is probably caused by the use of wrong version of python. I have tried every method to change the python version to python2, but it did not help. I have no idea what to do now. Can somebody help?

**Comment by mikeferguson** [comment]
Honestly, that is probably the least of your issues - this package has not been updated to Python3 and so there are probably lots of issues (especially in the binary processing of messages to the arbotix)

**Comment by mikeferguson** [comment]
resolved in #46
