### ISSUE TITLE
Unify gripper controllers, make action-based

### ISSUE THREAD

**Issue by mikeferguson** [vanadiumlabs/arbotix_ros#5]
This is already started, but needs to be finished.

**Comment by mikeferguson** [comment]
All of the old non-action based gripper controllers are now marked deprecated, and will be removed in Indigo. The action-based controller still needs to implement functionality to determine when the goal is reached.

**Comment by corot** [comment]
@mikeferguson, I did what you request for the OneSideGripperModel. Do you want a PR? But I'm afraid you have nearly zero time to maintain this... :see_no_evil: Would you like some help?

btw, why you keep duplicated versions, one with py extension and the other without?

**Comment by mikeferguson** [comment]
Archiving shortly
