### ISSUE TITLE
Motor Ignores max_speed when plugged back in

### ISSUE THREAD

**Issue by dgiger42** [vanadiumlabs/arbotix_ros#50]
Here's a video demonstrating the issue:
https://youtu.be/Ed6hL4YUrWk

`max_speed` is set to `45` in a YAML file, and the motor typically follows this, but it ignores the limit if the turret is unplugged, moved, and plugged back in.  The video shows it moving normally once, and then moving fast while ignoring `max_speed`.

I used this command to move the turret:
`rostopic pub --once /projector/projector_servo_pan_joint/command std_msgs/Float64 "data: -1.57"` 

As the command suggests, the turret typically has a projector attached to it, which is why it moves once it is unplugged, and also the reason why it moving too fast could be problematic.

**Comment by mikeferguson** [comment]
Archiving shortly
