### ISSUE TITLE
Building packages from source

### ISSUE THREAD

**Issue by jean-moorman** [vanadiumlabs/arbotix_ros#51]
Hello, I am trying to get this repo working in an anaconda environment (my system is Ubuntu 20.04 btw) with ros-noetic but unfortunately the version of ros-noetic-arbotix available on the robostack channel has a default device port of 'dev/ttyUSB0', which my system does not have. I have tried modifying my site-packages files but apparently python is using hard-coded binaries so none of the changes are being used. Is there any way for me to build these packages (arbotix_msgs, arbotix_python, etc.) from source so that I can change this port value to something more suitable? Thanks a bunch!

**Comment by light-tech** [comment]
The port can be set in the YAML configuration file, c.f. http://edu.gaitech.hk/turtlebot/turtlebot-arm-pincher.html for example.

**Comment by mikeferguson** [comment]
Archiving shortly
