### ISSUE TITLE
Install from source on Raspberry-Pi 4

### ISSUE THREAD

**Issue by Papalight** [vanadiumlabs/arbotix_ros#53]
Hello! 

Is it possible to install `arbotix_ros` package in **Raspberry-Pi 4** from source?
What is the proper pipeline that I should follow in order to install the package from source (even if it is not an RPI-4)?

Thank you in advance!

PS. I have tried to install the package using the `sudo apt-get install ros-noetic-arbotix` on RPI-4 but it didn't work, although it worked just fine on my laptop.

**Comment by mikeferguson** [comment]
Archiving shortly
